### ISSUE TITLE
How can i do schönfinkeling?

### ISSUE THREAD

**Issue by nyufac** [pyos/dg#13]
Ar dg cannot into schönfinkeling?
```
>>> f = a b -> a + b
>>> f 2
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dg/repl.dg", line 102, in runrepl
    module._ = eval x module.__dict__
  File "<input>", line 1, in
TypeError: f() missing 1 required positional argument: 'b'
```

**Comment by rubik** [comment]
I don't think dg supports currying.

**Comment by pyos** [comment]
`bind f 2`
