### ISSUE TITLE
One of the website examples doesn't work

### ISSUE THREAD

**Issue by kirbyfan64** [pyos/dg#17]
```
fac = n ->
  #: Calculate a factorial.
  n < 0 => None
  n < 2 => 1
  otherwise => n * fac (n-1)

print $ fac 2
```

gives:

```
Traceback (most recent call last):
  File "/media/ryan/stuff/anaconda/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/ryan/stuff/anaconda/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/__main__.dg", line 77, in 
    mode != '-'  => repl.runfile $ open encoding: 'utf-8' $ head sys.argv
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/repl.dg", line 110, in runfile
    otherwise  => runcode $ compilefd fd $ getattr fd 'name' '<input>'
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/repl.dg", line 79, in runcode
    eval code md.__dict__
  File "x.dg", line 7, in 
    print $ fac 2
  File "x.dg", line 5, in fac
    otherwise => n * fac (n-1)
TypeError: 'int' object is not callable
```

**Comment by pyos** [comment]
It does work. The space between `-` and `1` is kind of important. Otherwise it's ambiguous whether thing like `a -1` mean "subtract 1 from a" or "call a with -1". (Yeah, the parser sucks.)

(Also, you forgot the `if`.)

**Comment by kirbyfan64** [comment]
@pyos Crap...can't believe I missed that. Sorry!
