### ISSUE TITLE
Odd lambda indentation

### ISSUE THREAD

**Issue by kirbyfan64** [pyos/dg#18]
This doesn't work:

```
ps = [1, 2, 3]
head $ filter (p -> m = p
                    m and 10) ps
```

(I know this seems stupid, but it's a simplified test case!) It gives:

```
Traceback (most recent call last):
  File "/media/ryan/stuff/anaconda/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/ryan/stuff/anaconda/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/__main__.dg", line 77, in 
    mode != '-'  => repl.runfile $ open encoding: 'utf-8' $ head sys.argv
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/repl.dg", line 110, in runfile
    otherwise  => runcode $ compilefd fd $ getattr fd 'name' '<input>'
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/dg/repl.dg", line 79, in runcode
    eval code md.__dict__
  File "i.dg", line 3, in 
    m and 10) ps
  File "<core:1.runtime.dg>", line 161, in head
  File "i.dg", line 3, in <lambda>
    m and 10) ps
UnboundLocalError: local variable 'm' referenced before assignment
```

But this works:

```
ps = [1, 2, 3]
head $ filter (p ->
  m = p
  m and 10) ps
```

It seems to be that `dg` parses the first one as:

```
ps = [1, 2, 3]
head $ filter (p -> m = (p m and 10)) ps
```

Is this a bug? I mean, I kind of found it surprising, since it works in most indentation-based languages.

**Comment by pyos** [comment]
It's actually parsed as `p -> m = p (m and 10)`.

In short, it doesn't matter what operator you align indentation to; only the difference compared to the previous line matters. If a block is indented, it is passed to the last operator on the previous line (which in this case happens to be an implicit empty operator, aka a function call) as the right-hand statement.

Not sure what indentation-based languages you refer to, though.

**Comment by kirbyfan64** [comment]
Ugh...I am *so* sorry. I seriously need to be more focused when I read....
