### ISSUE TITLE
No `hamlike` module for building gh-pages

### ISSUE THREAD

**Issue by ceremcem** [pyos/dg#40]
Building https://github.com/pyos/dg/tree/gh-pages requires `hamlike` module and there is no such module [anywhere we can easily find](https://www.google.com.tr/search?q=python+hamlike&oq=python+hamlike&aqs=chrome..69i57j69i61j69i60l2j0l2.2814j0j4&sourceid=chrome&ie=UTF-8#q=python+hamlike+module):

```sh
make 
find * \( -type d -empty -o -name index.html -o -name '*.pyc' -o -name '*.gen.*' \) -delete
/usr/bin/env python3 -m dg build.dg src . /css/site.sass
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ceremcem/.local/lib/python3.5/site-packages/dg/__main__.dg", line 80, in 
    mode != '-'  => repl.runfile $ open encoding: 'utf-8' $ head sys.argv
  File "/home/ceremcem/.local/lib/python3.5/site-packages/dg/repl.dg", line 118, in runfile
    otherwise  => runcode $ compilefd fd $ getattr fd 'name' '<input>'
  File "/home/ceremcem/.local/lib/python3.5/site-packages/dg/repl.dg", line 81, in runcode
    eval code md.__dict__
  File "build.dg", line 5, in 
    import '/dmark'
  File "<core:1.runtime.dg>", line 297, in exec_module
  File "./dmark.dg", line 5, in 
    import '/hamlike/Hamlike'
ImportError: No module named 'hamlike'
Makefile:12: recipe for target 'css-site' failed
make: *** [css-site] Error 1
```

**Comment by pyos** [comment]
it wants this piece of crap: https://github.com/pyos/jinja-hamlike

should've added a requirements.txt, i guess...

**Comment by pyos** [comment]
Since it's just a single file, I decided to simply package it with the gh-pages branch.
