### ISSUE TITLE
`ImportError: python implementation 'pypy3-510' not supported`

### ISSUE THREAD

**Issue by TheRealC05** [pyos/dg#43]
I succefuly installed dg on pypy3, but when I want to use it, it throws some error: 
```
$ pypy3 -m dg
Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/__init__.py", line 16, in load
    with open(os.path.join(BUNDLE_DIR, PY_TAG + '.dgbundle'), 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/bundle/pypy3-510.dgbundle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/__init__.py", line 21, in load
    with open(os.path.join(BUNDLE_DIR, PY_TAG + '.dgbundle.py')) as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/bundle/pypy3-510.dgbundle.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/lib-python/3/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/__init__.py", line 27, in <module>
    load()
  File "/usr/local/Cellar/pypy3/5.10.1/libexec/site-packages/dg/__init__.py", line 25, in load
    raise ImportError('python implementation {!r} not supported'.format(PY_TAG))
ImportError: python implementation 'pypy3-510' not supported
```
So how can I fix it?

**Comment by pyos** [comment]
Well, you could try copying bundle/pypy3-57.dgbundle to bundle/pypy3-510.dgbundle, it may be compatible. If not, running `python3 -m dg -b pypy3-510 $(pypy3 -c "import sys; print(sys.hexversion)") && pypy3 -m dg -b` should create a valid bundle.

**Comment by pyos** [comment]
Okay, no, that won't work, pypy3 5.10 has an incompatible bytecode format. I'll look into this.

**Comment by pyos** [comment]
Added the bundle to the repository.
